### ISSUE TITLE
Create a Recipe app

### ISSUE THREAD

**Issue by MarkoKermi** [MarkoKermi/recipe_app_ror#3]
Hi, 
In this project me and @Tobby8629 will work on creating a recipe app based on the requirements that we also implement on the kanban board (see the link bellow). In this board we split all the activities so we can have equal contribution on the project. 

https://github.com/users/MarkoKermi/projects/2/views/1

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct project table ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! Kindly you forgot to `assign` your coding partner(`@Tobby8629`) these tasks: `{#12, #16, #17, #18, #19}` and also implement `group tasks` and assign to all team members 🙏🏼 

![image](https://github.com/MarkoKermi/recipe_app_ror/assets/63915024/6ec8153f-66f4-4e1c-b0a5-87622a7f9805)
  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarkoKermi** [comment]
Thx for the review we just did the changes that were required here is the link bellow:
https://github.com/users/MarkoKermi/projects/4

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️

Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ Good work so far

 ## Required Changes ♻️

Only one task has an assignee on the [project link](https://github.com/users/MarkoKermi/projects/4) you submitted as updated link.
![image](https://github.com/MarkoKermi/recipe_app_ror/assets/84156714/206e9e61-652d-4e50-8cf0-5425ba29bda5)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarkoKermi** [comment]
@bobb-Rob Thx for the review I submitted the wrong link here is the new one 
https://github.com/users/MarkoKermi/projects/6

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @mukhammadrizooff, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

Cheers and Happy coding!👏👏👏
